package com.bbb.exercise.agentdemo.ragservice.persistence;

import com.bbb.exercise.agentdemo.api.identity.ChatIdentity;
import com.bbb.exercise.agentdemo.api.rag.RagContracts.*;
import com.bbb.exercise.agentdemo.ragservice.domain.RagData.*;
import com.bbb.exercise.agentdemo.ragservice.domain.RagException;
import com.bbb.exercise.agentdemo.ragservice.chunking.SemanticChunker;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.support.TransactionTemplate;
import org.springframework.stereotype.Repository;
import org.springframework.http.HttpStatus;
import java.util.*;
import java.sql.ResultSet;
import java.sql.SQLException;

/** MySQL is authoritative. Every durable write from workers is fenced in a short transaction. */
@Repository
public class RagRepository {
    private final JdbcTemplate db;private final TransactionTemplate tx;private final Gson json=new Gson();
    public RagRepository(JdbcTemplate db,org.springframework.transaction.PlatformTransactionManager manager){this.db=db;this.tx=new TransactionTemplate(manager);}
    public DocumentView register(ChatIdentity who,String request,String filename,String hash,String path) {
        return tx.execute(s->{
            List<Map<String,Object>> existing=db.queryForList("SELECT document_id,content_hash FROM rag_document WHERE tenant_id=? AND user_id=? AND request_id=? FOR UPDATE",who.tenantId(),who.userId(),request);
            if(!existing.isEmpty()){if(!hash.equals(existing.getFirst().get("content_hash")))throw conflict("IDEMPOTENCY_CONFLICT");return document(who,(String)existing.getFirst().get("document_id"));}
            String id=UUID.randomUUID().toString();
            db.update("INSERT INTO rag_document(document_id,tenant_id,user_id,request_id,filename,content_hash,storage_path,status,index_status,summary_status) VALUES(?,?,?,?,?,?,?,'UPLOADED','PENDING','PENDING')",id,who.tenantId(),who.userId(),request,filename,hash,path);
            db.update("INSERT INTO rag_job(document_id,tenant_id,user_id,index_version,stage) VALUES(?,?,?,1,'UPLOADED')",id,who.tenantId(),who.userId());
            return document(who,id);
        });
    }
    public DocumentView document(ChatIdentity who,String id) {
        var result=db.query("SELECT * FROM rag_document WHERE document_id=? AND tenant_id=? AND user_id=? AND deleted=FALSE",(r,n)->view(r),id,who.tenantId(),who.userId());
        if(result.isEmpty())throw missing();return result.getFirst();
    }
    public List<DocumentView> documents(ChatIdentity who){return db.query("SELECT * FROM rag_document WHERE tenant_id=? AND user_id=? AND deleted=FALSE ORDER BY created_at DESC LIMIT 100",(r,n)->view(r),who.tenantId(),who.userId());}
    public boolean usesPath(ChatIdentity who,String document,String path){return Integer.valueOf(1).equals(db.queryForObject("SELECT COUNT(*) FROM rag_document WHERE tenant_id=? AND user_id=? AND document_id=? AND storage_path=?",Integer.class,who.tenantId(),who.userId(),document,path));}
    private static DocumentView view(ResultSet r)throws SQLException{return new DocumentView(r.getString("document_id"),r.getString("filename"),r.getString("status"),r.getString("index_status"),r.getString("summary_status"),r.getInt("chunk_count"),r.getInt("completed_chunks"),r.getString("error"),r.getInt("index_version"),r.getTimestamp("updated_at").toInstant().toString());}
    public SummaryView summary(ChatIdentity who,String id){document(who,id);return db.queryForObject("SELECT summary_status,summary_text,summary_covered,chunk_count FROM rag_document WHERE document_id=? AND tenant_id=? AND user_id=? AND deleted=FALSE",(r,n)->new SummaryView(r.getString(1),r.getString(2),r.getInt(4)==0?0:(double)r.getInt(3)/r.getInt(4)),id,who.tenantId(),who.userId());}
    public void delete(ChatIdentity who,String id){tx.executeWithoutResult(s->{document(who,id);db.update("UPDATE rag_document SET deleted=TRUE,status='CANCELLED',updated_at=CURRENT_TIMESTAMP(6) WHERE document_id=? AND tenant_id=? AND user_id=?",id,who.tenantId(),who.userId());db.update("UPDATE rag_job SET stage='CLEANUP',fence=fence+1,lease_until=NULL,available_at=CURRENT_TIMESTAMP(6) WHERE document_id=? AND tenant_id=? AND user_id=?",id,who.tenantId(),who.userId());});}
    public DocumentView retry(ChatIdentity who,String id){return tx.execute(s->{
        var documents=db.queryForList("SELECT * FROM rag_document WHERE document_id=? AND tenant_id=? AND user_id=? AND deleted=FALSE FOR UPDATE",id,who.tenantId(),who.userId());if(documents.isEmpty())throw missing();var row=documents.getFirst();
        if(!Set.of("FAILED","WAITING_FOR_BUDGET","WAITING_FOR_RECONCILIATION").contains(row.get("status")))return document(who,id);
        boolean rebuild="EMBEDDING_REBUILD_REQUIRED".equals(row.get("error"));String stage=!rebuild&&"READY".equals(row.get("index_status"))?"SUMMARIZING":"UPLOADED";
        if(rebuild){int next=((Number)row.get("processing_version")).intValue()+1;db.update("UPDATE rag_job SET index_version=?,embedding_fingerprint=NULL,parsed_path=NULL WHERE document_id=?",next,id);db.update("UPDATE rag_document SET processing_version=?,summary_covered=0 WHERE document_id=?",next,id);}
        db.update("UPDATE rag_job SET stage=?,lease_until=NULL,available_at=CURRENT_TIMESTAMP(6),fence=fence+1 WHERE document_id=? AND tenant_id=? AND user_id=?",stage,id,who.tenantId(),who.userId());
        db.update("UPDATE rag_document SET status=?,error=NULL,summary_status='PENDING',updated_at=CURRENT_TIMESTAMP(6) WHERE document_id=? AND tenant_id=? AND user_id=?",stage,id,who.tenantId(),who.userId());return document(who,id);
    });}
    public void bindEmbedding(Job job,String fingerprint){tx.executeWithoutResult(s->{lock(job);var row=db.queryForMap("SELECT embedding_fingerprint FROM rag_job WHERE document_id=? FOR UPDATE",job.id());String pinned=(String)row.get("embedding_fingerprint");if(pinned!=null&&!pinned.equals(fingerprint))throw conflict("EMBEDDING_REBUILD_REQUIRED");db.update("UPDATE rag_job SET embedding_fingerprint=? WHERE document_id=?",fingerprint,job.id());});}
    public void assertEmbedding(Scope scope,String fingerprint){for(var entry:scope.versions().entrySet()){var rows=db.queryForList("SELECT embedding_fingerprint FROM rag_document WHERE document_id=? AND tenant_id=? AND user_id=? AND index_version=? AND deleted=FALSE",entry.getKey(),scope.identity().tenantId(),scope.identity().userId(),entry.getValue());if(rows.isEmpty())throw missing();if(!fingerprint.equals(rows.getFirst().get("embedding_fingerprint")))throw conflict("EMBEDDING_REBUILD_REQUIRED");}}
    public Optional<Job> claim(){return tx.execute(s->{
        var jobs=db.query("SELECT j.*,d.storage_path,d.filename FROM rag_job j JOIN rag_document d ON d.document_id=j.document_id WHERE j.stage IN ('UPLOADED','PARSING','CHUNKING','EMBEDDING','INDEXING','SUMMARIZING','CLEANUP') AND j.available_at<=CURRENT_TIMESTAMP(6) AND (j.lease_until IS NULL OR j.lease_until<CURRENT_TIMESTAMP(6)) ORDER BY j.available_at LIMIT 1 FOR UPDATE SKIP LOCKED",(r,n)->new Job(r.getString("document_id"),new ChatIdentity(r.getString("tenant_id"),r.getString("user_id"),true),r.getInt("index_version"),r.getLong("fence")+1,r.getString("stage"),r.getString("storage_path"),r.getString("filename")));
        if(jobs.isEmpty())return Optional.empty();Job job=jobs.getFirst();db.update("UPDATE rag_job SET fence=?,lease_until=TIMESTAMPADD(SECOND,180,CURRENT_TIMESTAMP(6)),updated_at=CURRENT_TIMESTAMP(6) WHERE document_id=?",job.fence(),job.id());return Optional.of(job);
    });}
    private void lock(Job job){var rows=db.queryForList("SELECT fence FROM rag_job WHERE document_id=? AND tenant_id=? AND user_id=? AND index_version=? AND fence=? AND lease_until>CURRENT_TIMESTAMP(6) FOR UPDATE",job.id(),job.identity().tenantId(),job.identity().userId(),job.version(),job.fence());if(rows.isEmpty())throw conflict("STALE_JOB_LEASE");}
    public void heartbeat(Job job){int changed=db.update("UPDATE rag_job SET lease_until=TIMESTAMPADD(SECOND,180,CURRENT_TIMESTAMP(6)) WHERE document_id=? AND tenant_id=? AND user_id=? AND index_version=? AND fence=? AND lease_until>CURRENT_TIMESTAMP(6)",job.id(),job.identity().tenantId(),job.identity().userId(),job.version(),job.fence());if(changed!=1)throw conflict("STALE_JOB_LEASE");}
    public void parsed(Job job,String path){tx.executeWithoutResult(s->{lock(job);db.update("UPDATE rag_job SET parsed_path=?,stage='CHUNKING' WHERE document_id=?",path,job.id());});}
    public String parsedPath(Job job){return db.queryForObject("SELECT parsed_path FROM rag_job WHERE document_id=? AND tenant_id=? AND user_id=? AND index_version=? AND fence=?",String.class,job.id(),job.identity().tenantId(),job.identity().userId(),job.version(),job.fence());}
    public void stage(Job job,String stage){tx.executeWithoutResult(s->{lock(job);db.update("UPDATE rag_job SET stage=?,updated_at=CURRENT_TIMESTAMP(6) WHERE document_id=?",stage,job.id());db.update("UPDATE rag_document SET status=?,summary_status=CASE WHEN ?='SUMMARIZING' THEN 'PROCESSING' ELSE summary_status END,updated_at=CURRENT_TIMESTAMP(6) WHERE document_id=? AND tenant_id=? AND user_id=? AND deleted=FALSE",stage,stage,job.id(),job.identity().tenantId(),job.identity().userId());});}
    public void park(Job job,String state,String error){tx.executeWithoutResult(s->{lock(job);db.update("UPDATE rag_job SET stage=?,lease_until=NULL,updated_at=CURRENT_TIMESTAMP(6) WHERE document_id=?",state,job.id());db.update("UPDATE rag_document SET status=?,error=?,summary_status=CASE WHEN index_status='READY' THEN ? ELSE summary_status END,updated_at=CURRENT_TIMESTAMP(6) WHERE document_id=? AND tenant_id=? AND user_id=? AND deleted=FALSE",state,error,state,job.id(),job.identity().tenantId(),job.identity().userId());});}
    public void yield(Job job){tx.executeWithoutResult(s->{lock(job);db.update("UPDATE rag_job SET lease_until=NULL,available_at=TIMESTAMPADD(SECOND,2,CURRENT_TIMESTAMP(6)) WHERE document_id=?",job.id());});}
    public void saveChunks(Job job,List<Chunk> chunks){tx.executeWithoutResult(s->{lock(job);for(Chunk c:chunks)db.update("INSERT INTO rag_chunk(chunk_id,document_id,tenant_id,user_id,index_version,text,title,page,source_ordinal,char_start,char_end,content_hash,embedding_fingerprint) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,(SELECT embedding_fingerprint FROM rag_job WHERE document_id=?)) ON DUPLICATE KEY UPDATE text=VALUES(text)",c.id(),job.id(),job.identity().tenantId(),job.identity().userId(),job.version(),c.text(),c.title(),c.page(),c.ordinal(),c.charStart(),c.charEnd(),c.hash(),job.id());db.update("UPDATE rag_document SET chunk_count=?,updated_at=CURRENT_TIMESTAMP(6) WHERE document_id=?",chunks.size(),job.id());});}
    public List<Chunk> chunks(ChatIdentity who,String document,int version){return db.query("SELECT * FROM rag_chunk WHERE tenant_id=? AND user_id=? AND document_id=? AND index_version=? ORDER BY char_start,chunk_id",(r,n)->chunk(r),who.tenantId(),who.userId(),document,version);}
    private static Chunk chunk(ResultSet r)throws SQLException{Integer page=(Integer)r.getObject("page");return new Chunk(r.getString("chunk_id"),r.getString("document_id"),r.getInt("index_version"),r.getString("text"),r.getString("title"),page,r.getInt("source_ordinal"),r.getInt("char_start"),r.getInt("char_end"),r.getString("content_hash"),r.getString("embedding_fingerprint"));}
    public Optional<List<Float>> cached(ChatIdentity who,String key){var rows=db.queryForList("SELECT vector_json FROM rag_embedding_cache WHERE cache_key=? AND tenant_id=? AND user_id=?",key,who.tenantId(),who.userId());return rows.isEmpty()?Optional.empty():Optional.of(json.fromJson((String)rows.getFirst().get("vector_json"),new TypeToken<List<Float>>(){}.getType()));}
    public void cache(Job job,String key,List<Float> vector,String call,long tokens,int dimensions,String fingerprint){tx.executeWithoutResult(s->{lock(job);db.update("INSERT INTO rag_embedding_cache(cache_key,tenant_id,user_id,model,dimensions,processing_version,vector_json,call_id,input_tokens,model_fingerprint) VALUES(?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE vector_json=VALUES(vector_json)",key,job.identity().tenantId(),job.identity().userId(),fingerprint,dimensions,SemanticChunker.VERSION,json.toJson(vector),call,tokens,fingerprint);});}
    public void indexed(Job job,List<Chunk> batch){tx.executeWithoutResult(s->{lock(job);for(Chunk c:batch)db.update("UPDATE rag_chunk SET indexed=TRUE WHERE chunk_id=? AND tenant_id=? AND user_id=? AND index_version=?",c.id(),job.identity().tenantId(),job.identity().userId(),job.version());db.update("UPDATE rag_document SET completed_chunks=(SELECT COUNT(*) FROM rag_chunk WHERE document_id=? AND index_version=? AND indexed=TRUE),updated_at=CURRENT_TIMESTAMP(6) WHERE document_id=?",job.id(),job.version(),job.id());});}
    public boolean isIndexed(Job job,String chunk){return Boolean.TRUE.equals(db.queryForObject("SELECT indexed FROM rag_chunk WHERE chunk_id=? AND tenant_id=? AND user_id=? AND index_version=?",Boolean.class,chunk,job.identity().tenantId(),job.identity().userId(),job.version()));}
    public void indexReady(Job job){tx.executeWithoutResult(s->{lock(job);Integer remaining=db.queryForObject("SELECT COUNT(*) FROM rag_chunk WHERE document_id=? AND tenant_id=? AND user_id=? AND index_version=? AND indexed=FALSE",Integer.class,job.id(),job.identity().tenantId(),job.identity().userId(),job.version());if(remaining==null||remaining!=0)throw conflict("INDEX_INCOMPLETE");db.update("UPDATE rag_document SET index_version=?,embedding_fingerprint=(SELECT embedding_fingerprint FROM rag_job WHERE document_id=?),index_status='READY',updated_at=CURRENT_TIMESTAMP(6) WHERE document_id=? AND tenant_id=? AND user_id=? AND deleted=FALSE",job.version(),job.id(),job.id(),job.identity().tenantId(),job.identity().userId());});}
    public Optional<SummaryNode> summaryNode(Job job,String node){var rows=db.query("SELECT * FROM rag_summary_node WHERE document_id=? AND tenant_id=? AND user_id=? AND index_version=? AND node_id=? AND prompt_version='summary-v1'",(r,n)->new SummaryNode(r.getString("node_id"),r.getInt("first_chunk"),r.getInt("last_chunk"),r.getString("text")),job.id(),job.identity().tenantId(),job.identity().userId(),job.version(),node);return rows.stream().findFirst();}
    public void saveSummary(Job job,SummaryNode node,String call,long input,long output){tx.executeWithoutResult(s->{lock(job);db.update("INSERT INTO rag_summary_node(document_id,tenant_id,user_id,index_version,node_id,prompt_version,first_chunk,last_chunk,text,call_id,input_tokens,output_tokens) VALUES(?,?,?,?,?,'summary-v1',?,?,?,?,?,?) ON DUPLICATE KEY UPDATE text=VALUES(text)",job.id(),job.identity().tenantId(),job.identity().userId(),job.version(),node.id(),node.first(),node.last(),node.text(),call,input,output);});}
    public void summaryProgress(Job job,int covered){tx.executeWithoutResult(s->{lock(job);db.update("UPDATE rag_document SET summary_covered=?,updated_at=CURRENT_TIMESTAMP(6) WHERE document_id=? AND tenant_id=? AND user_id=?",covered,job.id(),job.identity().tenantId(),job.identity().userId());});}
    public void summaryReady(Job job,String text,int covered){tx.executeWithoutResult(s->{lock(job);db.update("UPDATE rag_document SET summary_text=?,summary_covered=?,summary_status='READY',status='READY',error=NULL,updated_at=CURRENT_TIMESTAMP(6) WHERE document_id=? AND tenant_id=? AND user_id=? AND deleted=FALSE AND chunk_count=?",text,covered,job.id(),job.identity().tenantId(),job.identity().userId(),covered);db.update("UPDATE rag_job SET stage='READY',lease_until=NULL WHERE document_id=?",job.id());});}
    public void cleanupComplete(Job job){tx.executeWithoutResult(s->{lock(job);db.update("DELETE FROM rag_chunk WHERE document_id=? AND tenant_id=? AND user_id=?",job.id(),job.identity().tenantId(),job.identity().userId());db.update("DELETE FROM rag_summary_node WHERE document_id=? AND tenant_id=? AND user_id=?",job.id(),job.identity().tenantId(),job.identity().userId());db.update("UPDATE rag_job SET stage='CANCELLED',lease_until=NULL WHERE document_id=?",job.id());});}
    public ConversationView createConversation(ChatIdentity who,List<String> ids){if(ids==null||ids.isEmpty()||ids.size()>8||new HashSet<>(ids).size()!=ids.size())throw conflict("DOCUMENT_SCOPE_INVALID");return tx.execute(s->{var versions=new LinkedHashMap<String,Integer>();for(String id:ids){var doc=document(who,id);if(!doc.indexStatus().equals("READY"))throw conflict("INDEX_NOT_READY");versions.put(id,doc.indexVersion());}String id=UUID.randomUUID().toString();db.update("INSERT INTO rag_conversation(conversation_id,tenant_id,user_id,versions_json) VALUES(?,?,?,?)",id,who.tenantId(),who.userId(),json.toJson(versions));return new ConversationView(id,List.copyOf(ids),versions,List.of());});}
    public Scope scope(ChatIdentity who,String id){var rows=db.queryForList("SELECT versions_json FROM rag_conversation WHERE conversation_id=? AND tenant_id=? AND user_id=?",id,who.tenantId(),who.userId());if(rows.isEmpty())throw missing();Map<String,Integer> versions=json.fromJson((String)rows.getFirst().get("versions_json"),new TypeToken<Map<String,Integer>>(){}.getType());for(var entry:versions.entrySet()){DocumentView d=document(who,entry.getKey());if(!d.indexStatus().equals("READY")||d.indexVersion()!=entry.getValue())throw conflict("DOCUMENT_VERSION_CHANGED");}return new Scope(who,versions);}
    private Scope lockedScope(ChatIdentity who,String id){var conversations=db.queryForList("SELECT versions_json FROM rag_conversation WHERE conversation_id=? AND tenant_id=? AND user_id=? FOR UPDATE",id,who.tenantId(),who.userId());if(conversations.isEmpty())throw missing();Map<String,Integer> versions=json.fromJson((String)conversations.getFirst().get("versions_json"),new TypeToken<Map<String,Integer>>(){}.getType());for(var entry:versions.entrySet()){var documents=db.queryForList("SELECT index_status,index_version,deleted FROM rag_document WHERE document_id=? AND tenant_id=? AND user_id=? FOR UPDATE",entry.getKey(),who.tenantId(),who.userId());if(documents.isEmpty()||Boolean.TRUE.equals(documents.getFirst().get("deleted")))throw missing();var row=documents.getFirst();if(!"READY".equals(row.get("index_status"))||((Number)row.get("index_version")).intValue()!=entry.getValue())throw conflict("DOCUMENT_VERSION_CHANGED");}return new Scope(who,versions);}
    public ConversationView conversation(ChatIdentity who,String id){Scope scope=scope(who,id);return new ConversationView(id,List.copyOf(scope.versions().keySet()),scope.versions(),history(who,id));}
    public List<History> history(ChatIdentity who,String id){return db.query("SELECT call_id,question,answer_json FROM rag_answer WHERE tenant_id=? AND user_id=? AND conversation_id=? AND status='COMPLETED' ORDER BY updated_at DESC LIMIT 12",(r,n)->new History(r.getString(1),r.getString(2),json.fromJson(r.getString(3),Answer.class)),who.tenantId(),who.userId(),id).reversed();}
    public AnswerLease begin(ChatIdentity who,AnswerRequest request){String hash=SemanticChunker.hash(request.conversationId()+"\n"+request.question());return tx.execute(s->{lockedScope(who,request.conversationId());var rows=db.queryForList("SELECT *,CASE WHEN lease_until>CURRENT_TIMESTAMP(6) THEN 1 ELSE 0 END AS live FROM rag_answer WHERE tenant_id=? AND user_id=? AND call_id=? FOR UPDATE",who.tenantId(),who.userId(),request.callId());if(rows.isEmpty()){db.update("INSERT INTO rag_answer(call_id,tenant_id,user_id,conversation_id,request_hash,question,status,lease_until) VALUES(?,?,?,?,?,?,'RUNNING',TIMESTAMPADD(SECOND,300,CURRENT_TIMESTAMP(6)))",request.callId(),who.tenantId(),who.userId(),request.conversationId(),hash,request.question());return new AnswerLease(1,null);}var row=rows.getFirst();if(!hash.equals(row.get("request_hash")))throw conflict("CALL_ID_PARAMETER_CONFLICT");if("COMPLETED".equals(row.get("status")))return new AnswerLease(((Number)row.get("fence")).longValue(),json.fromJson((String)row.get("answer_json"),Answer.class));if(((Number)row.get("live")).intValue()>0)throw conflict("ANSWER_IN_PROGRESS");long fence=((Number)row.get("fence")).longValue()+1;db.update("UPDATE rag_answer SET status='RUNNING',fence=?,lease_until=TIMESTAMPADD(SECOND,300,CURRENT_TIMESTAMP(6)) WHERE tenant_id=? AND user_id=? AND call_id=?",fence,who.tenantId(),who.userId(),request.callId());return new AnswerLease(fence,null);});}
    public void renewAnswer(ChatIdentity who,AnswerRequest request,long fence){tx.executeWithoutResult(s->{lockedScope(who,request.conversationId());int updated=db.update("UPDATE rag_answer SET lease_until=TIMESTAMPADD(SECOND,300,CURRENT_TIMESTAMP(6)) WHERE tenant_id=? AND user_id=? AND call_id=? AND conversation_id=? AND fence=? AND status='RUNNING' AND lease_until>CURRENT_TIMESTAMP(6)",who.tenantId(),who.userId(),request.callId(),request.conversationId(),fence);if(updated!=1)throw conflict("STALE_ANSWER_LEASE");});}
    public void commit(ChatIdentity who,AnswerRequest request,long fence,Answer answer){tx.executeWithoutResult(s->{lockedScope(who,request.conversationId());int updated=db.update("UPDATE rag_answer SET status='COMPLETED',answer_json=?,lease_until=NULL,updated_at=CURRENT_TIMESTAMP(6) WHERE tenant_id=? AND user_id=? AND call_id=? AND fence=? AND status='RUNNING' AND lease_until>CURRENT_TIMESTAMP(6)",json.toJson(answer),who.tenantId(),who.userId(),request.callId(),fence);if(updated!=1)throw conflict("STALE_ANSWER_LEASE");});}
    public void answerError(ChatIdentity who,AnswerRequest request,long fence,String state){db.update("UPDATE rag_answer SET status=?,lease_until=NULL,updated_at=CURRENT_TIMESTAMP(6) WHERE tenant_id=? AND user_id=? AND call_id=? AND fence=?",state,who.tenantId(),who.userId(),request.callId(),fence);}
    public void trace(ChatIdentity who,String conversation,String call,String phase,Object payload){db.update("INSERT INTO rag_trace(trace_id,tenant_id,user_id,conversation_id,call_id,phase,payload_json) VALUES(?,?,?,?,?,?,?)",UUID.randomUUID().toString(),who.tenantId(),who.userId(),conversation,call,phase,json.toJson(payload));}
    public List<Map<String,Object>> retrievalTraces(ChatIdentity who,String conversation){scope(who,conversation);return db.query("SELECT call_id,payload_json,created_at FROM rag_trace WHERE tenant_id=? AND user_id=? AND conversation_id=? AND phase='RETRIEVAL' ORDER BY created_at DESC LIMIT 20",(r,n)->Map.of("callId",r.getString(1),"payload",json.fromJson(r.getString(2),Object.class),"createdAt",r.getTimestamp(3).toInstant().toString()),who.tenantId(),who.userId(),conversation);}
    public <T>Optional<T> snapshot(ChatIdentity who,String composite,String stage,Class<T> type){var rows=db.queryForList("SELECT payload_json FROM rag_stage_snapshot WHERE tenant_id=? AND user_id=? AND composite_id=? AND stage=?",who.tenantId(),who.userId(),composite,stage);return rows.isEmpty()?Optional.empty():Optional.of(json.fromJson((String)rows.getFirst().get("payload_json"),type));}
    public <T>T saveSnapshot(ChatIdentity who,String composite,String stage,T payload,Class<T> type){db.update("INSERT IGNORE INTO rag_stage_snapshot(tenant_id,user_id,composite_id,stage,payload_json) VALUES(?,?,?,?,?)",who.tenantId(),who.userId(),composite,stage,json.toJson(payload));return snapshot(who,composite,stage,type).orElseThrow();}
    public static RagException conflict(String code){return new RagException(code,HttpStatus.CONFLICT);}private static RagException missing(){return new RagException("DOCUMENT_OR_CONVERSATION_NOT_FOUND",HttpStatus.NOT_FOUND);}
    public record SummaryNode(String id,int first,int last,String text){}
    public record AnswerLease(long fence,Answer completed){}
}
