package com.bbb.exercise.agentdemo.ragservice.retrieval;
import com.bbb.exercise.agentdemo.api.identity.ChatIdentity;
import com.bbb.exercise.agentdemo.ragservice.domain.RagData.*;
import io.milvus.v2.client.*;
import io.milvus.v2.common.*;
import io.milvus.common.clientenum.FunctionType;
import io.milvus.v2.service.collection.request.*;
import io.milvus.v2.service.vector.request.*;
import io.milvus.v2.service.vector.request.data.*;
import com.google.gson.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import jakarta.annotation.PreDestroy;
import java.util.*;

/** Java v2 SDK 2.6.4, Milvus 2.6.2 official matrix. Sparse vectors are generated by server BM25. */
@Component
public class MilvusVectorIndex implements VectorIndex {
    private final String uri,token,collection;private final int dimensions;private volatile MilvusClientV2 client;
    public MilvusVectorIndex(@Value("${rag.milvus.uri:http://127.0.0.1:19530}") String uri,@Value("${rag.milvus.token:}") String token,@Value("${rag.milvus.collection:agent_rag_v2}") String collection,@Value("${rag.dimensions:1024}") int dimensions){this.uri=uri;this.token=token;this.collection=collection;this.dimensions=dimensions;if(!collection.matches("[A-Za-z_][A-Za-z0-9_]{0,127}"))throw new IllegalArgumentException("Collection name");}
    private synchronized MilvusClientV2 client(){
        if(client!=null)return client;
        MilvusClientV2 candidate=new MilvusClientV2(ConnectConfig.builder().uri(uri).token(token).connectTimeoutMs(5000L).rpcDeadlineMs(30000L).build());
        try{
            if(!candidate.hasCollection(HasCollectionReq.builder().collectionName(collection).build())){
                var schema=CreateCollectionReq.CollectionSchema.builder().enableDynamicField(false).build();
                schema.addField(AddFieldReq.builder().fieldName("chunk_id").dataType(DataType.VarChar).maxLength(64).isPrimaryKey(true).autoID(false).build());
                for(String field:List.of("tenant_id","user_id","document_id"))schema.addField(AddFieldReq.builder().fieldName(field).dataType(DataType.VarChar).maxLength(512).build());
                schema.addField(AddFieldReq.builder().fieldName("index_version").dataType(DataType.Int64).build());
                schema.addField(AddFieldReq.builder().fieldName("embedding_fingerprint").dataType(DataType.VarChar).maxLength(64).build());
                // Custom jieba+lowercase preserves ASCII part numbers alongside Chinese terms.
                schema.addField(AddFieldReq.builder().fieldName("text").dataType(DataType.VarChar).maxLength(16384).enableAnalyzer(true).analyzerParams(Map.of("tokenizer","jieba","filter",List.of("lowercase"))).build());
                schema.addField(AddFieldReq.builder().fieldName("dense").dataType(DataType.FloatVector).dimension(dimensions).build());
                schema.addField(AddFieldReq.builder().fieldName("sparse").dataType(DataType.SparseFloatVector).build());
                schema.addFunction(CreateCollectionReq.Function.builder().name("text_bm25").functionType(FunctionType.BM25).inputFieldNames(List.of("text")).outputFieldNames(List.of("sparse")).build());
                candidate.createCollection(CreateCollectionReq.builder().collectionName(collection).collectionSchema(schema).consistencyLevel(ConsistencyLevel.STRONG)
                  .indexParams(List.of(IndexParam.builder().fieldName("dense").indexType(IndexParam.IndexType.HNSW).metricType(IndexParam.MetricType.COSINE).extraParams(Map.of("M",16,"efConstruction",128)).build(),
                      IndexParam.builder().fieldName("sparse").indexType(IndexParam.IndexType.SPARSE_INVERTED_INDEX).metricType(IndexParam.MetricType.BM25).extraParams(Map.of("inverted_index_algo","DAAT_MAXSCORE","bm25_k1",1.2,"bm25_b",.75)).build())).build());
            }
            var described=candidate.describeCollection(DescribeCollectionReq.builder().collectionName(collection).build());
            if(!described.getFieldNames().contains("embedding_fingerprint")||!Objects.equals(described.getCollectionSchema().getField("dense").getDimension(),dimensions))throw new IllegalStateException("COLLECTION_SCHEMA_REBUILD_REQUIRED");
            candidate.loadCollection(LoadCollectionReq.builder().collectionName(collection).build());client=candidate;return client;
        }catch(RuntimeException e){candidate.close();throw e;}
    }
    public void upsert(ChatIdentity who,List<Chunk> chunks,List<List<Float>> vectors){
        if(chunks.size()!=vectors.size())throw new IllegalArgumentException("Vector count");var rows=new ArrayList<JsonObject>();
        for(int i=0;i<chunks.size();i++){Chunk c=chunks.get(i);List<Float> v=vectors.get(i);if(v.size()!=dimensions||v.stream().anyMatch(f->f==null||!Float.isFinite(f)))throw new IllegalArgumentException("Vector dimensions");JsonObject row=new JsonObject();row.addProperty("chunk_id",c.id());row.addProperty("tenant_id",who.tenantId());row.addProperty("user_id",who.userId());row.addProperty("document_id",c.documentId());row.addProperty("index_version",c.version());row.addProperty("text",c.text());row.add("dense",new Gson().toJsonTree(v));rows.add(row);}
        for(int i=0;i<rows.size();i++)rows.get(i).addProperty("embedding_fingerprint",chunks.get(i).embeddingFingerprint()==null?"legacy-unknown":chunks.get(i).embeddingFingerprint());
        client().upsert(UpsertReq.builder().collectionName(collection).data(rows).build());
    }
    public List<Hit> dense(Scope scope,List<Float> vector,int limit){return search(scope,new FloatVec(vector),"dense",IndexParam.MetricType.COSINE,limit);}
    public List<Hit> keyword(Scope scope,String query,int limit){return search(scope,new EmbeddedText(query),"sparse",IndexParam.MetricType.BM25,limit);}
    private List<Hit> search(Scope scope,BaseVector vector,String field,IndexParam.MetricType metric,int limit){
        var response=client().search(SearchReq.builder().collectionName(collection).annsField(field).data(List.of(vector)).topK(limit).filter(filter(scope)).metricType(metric)
                .outputFields(List.of("chunk_id","tenant_id","user_id","document_id","index_version")).consistencyLevel(ConsistencyLevel.STRONG).build());
        var hits=new ArrayList<Hit>();if(response.getSearchResults().isEmpty())return hits;
        for(var result:response.getSearchResults().getFirst()){var entity=result.getEntity();hits.add(new Hit(String.valueOf(result.getId()),String.valueOf(entity.get("document_id")),((Number)entity.get("index_version")).intValue(),String.valueOf(entity.get("tenant_id")),String.valueOf(entity.get("user_id")),result.getScore()));}return hits;
    }
    public static String filter(Scope scope){String document=String.join(" or ",scope.versions().entrySet().stream().map(e->"(document_id == "+quote(e.getKey())+" and index_version == "+e.getValue()+")").toList());return "tenant_id == "+quote(scope.identity().tenantId())+" and user_id == "+quote(scope.identity().userId())+" and ("+document+")"+(scope.embeddingFingerprint()==null?"":" and embedding_fingerprint == "+quote(scope.embeddingFingerprint()));}
    private static String quote(String value){return new GsonBuilder().disableHtmlEscaping().create().toJson(value);}
    public void remove(ChatIdentity who,String document){client().delete(DeleteReq.builder().collectionName(collection).filter("tenant_id == "+quote(who.tenantId())+" and user_id == "+quote(who.userId())+" and document_id == "+quote(document)).build());}
    public void verify(ChatIdentity who,String document,int version,int expected){var response=client().query(QueryReq.builder().collectionName(collection).filter(filter(new Scope(who,Map.of(document,version)))).outputFields(List.of("count(*)")).consistencyLevel(ConsistencyLevel.STRONG).build());if(response.getQueryResults().isEmpty()||((Number)response.getQueryResults().getFirst().getEntity().get("count(*)")).intValue()!=expected)throw new IllegalStateException("INDEX_READBACK_INCOMPLETE");}
    @PreDestroy public synchronized void close(){if(client!=null){client.close();client=null;}}
}
